name: "Publish container image to Dockerhub"

# triggers
on:
  workflow_dispatch:
  # push:
  # pull_request:

jobs:
  buildanddeploy:
    name: "Build and deploy all devcontainer images"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: "Docker Build and Publish"
        env:
          DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}
          DOCKERHUB_TKN: ${{ secrets.DOCKERHUB_TKN }}
        run: |
          echo "Dockerhub user: ${DOCKERHUB_USER}"
          docker login -u $DOCKERHUB_USER -p $DOCKERHUB_TKN
          bash -c .github/workflows/build-deploy.bash
