name: "Build and publish single devcontainers to Dockerhub"

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string

jobs:
  buildanddeploy:
    name: "Build and deploy single container image"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: "Docker Build and Publish"
        env:
          DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}
          DOCKERHUB_TKN: ${{ secrets.DOCKERHUB_TKN }}
        run: |
          echo "Dockerhub user: ${DOCKERHUB_USER}"
          docker login -u $DOCKERHUB_USER -p $DOCKERHUB_TKN
          TAG=${DOCKERHUB_USER}/devcontainer_${image}
          docker build -t $TAG -f ./${image}/Dockerfile .
          docker push $TAG
